//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        public int IdPerson { get; set; }
        public string Name { get; set; }
        public string surname { get; set; }
        public string Email { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public int IdUser { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
